version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
  rebase-strategy: disabled
