sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

jobs:
  include:
    - stage: "Tests"
      name: "Formatting"
      script: yarn run prettier

    - stage: "Tests"
      name: "Lint"
      script: yarn run lint

    - stage: "Tests"
      name: "Unit Tests"
      script: yarn run test

      # The next two stages are mutually exclusive through their `if` condition.
      # tl;dr This saves us from wasting snapshots on percy.io.

      # We have branch builds and pull-request builds activated in travis.
      # This means for each PR, travis runs two twice: one for the pushed branch and once for the pull request.
      # However, we don't need to capture the snapshot twice, that would just waste snapshots.
      # The tricky thing is, we cannot just disable branch builds because this would disable our continuous deployment to GitHub pages.
      # That is why for ordinary branches, we just run the UI-tests and for poll-requests and master branch, we capture the snapshots
      # so that we can use percy for visual review.

    - stage: "Tests"
      name: "UI Tests with percy snapshots"
      script: node_modules/.bin/percy exec -- cypress/run.sh
      if: (branch = master) OR (type = pull_request)

    - stage: "Tests"
      name: "UI Tests without percy snapshots"
      script: cypress/run.sh
      if: branch != master

    - stage: deploy
      name: "Deploy to Github Pages"
      before_deploy: yarn run build:prod
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: dist
          fqdn: nobt.io
          on:
            branch: master
            repo: nobt-io/frontend
      after_deploy: .sentry/upload-sourcemaps

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    rooms:
      - secure: Tuxfc7g/LiJSI8N6miC7/XTJjLd5q0Bq6vGGp176F7dfMelZIngZtJU2DRdmTm9Z5Y6ZZgFU2P0GtznGNIgmufzkiXrabbND8GkRfuLmtM7yBeVYNt7IvGDpk2DnQeLAyY7Gx9SBGoywq8KJJeRutyiX3A3FWYfKi3GckCA1wk/YS1buRG+SNle0Oj3/xsoAueSdD+6jiFjFEX5FdTQXWB1gKamkFhUC4hgyruVG4LyXi2GH79xm58GhsxyGo6THURGmwCrRSe4GRocxhkruBGJ3Jh+Epf8d/8OgOYcFXDi4cP9ppQemUL0Egvqh+4NFF29d/7mMB1M1zUPQ9by4D3pSD0H+zPiDSeC85XJAh8z4zFtybzeRPE0SDiQLRLeSzeX4QKe3meymcWFMYAbMrGGMmrm1K98broQ7pYIDmlETrJVmIGA3xfsqFPO0ZQi4SobsOemeAgZvJcyzS6Fuaa1JpYYlsk2GBP3fK0kUmipMsINploUH6GqrwO9a3h1TERFvmYwVidgYodR0xzdFaFpTIkxI0FMeLkoyKN0bO2njJB1plMWM+8x83g5xJuYnP90uayL5ipHNVD8bYivZNd84wTq+PAIr6yNY/NIDmVDb+CUwsnpJYF3mvKVQf5rnF37UO9YG8FErFLmOeCWIZRgUNTa5Vr+vRFdQ7qd2zBA=
    on_success: change
    on_failure: always
    on_pull_requests: true
