sudo: false
language: node_js
node_js:
- '8'
cache: yarn
install:
- yarn install --non-interactive
script:
- yarn run compile
- yarn run test
- yarn run lint
before_deploy:
- pip install --user awscli
- yarn run deploy
deploy:
  - provider: script
    skip_cleanup: true
    script: .aws/deploy
    access_key_id: AKIAIF35EA6NPCKM7MXA
    on:
      branch: master
      repo: nobt-io/frontend
  - provider: script
    skip_cleanup: true
    script: .sentry/upload-sourcemaps
    on:
      branch: master
      repo: nobt-io/frontend
