sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run compile
- npm run test
before_deploy: pip install --user awscli
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npm run deploy
      - ~/.local/bin/aws s3 sync dist s3://nobt.io --region=eu-central-1 --delete --acl=public-read
    access_key_id: AKIAIF35EA6NPCKM7MXA
    on:
      branch: master
      repo: nobt-io/frontend
  - provider: script
    skip_cleanup: true
    script: .sentry/upload-sourcemaps
    on:
      branch: master
      repo: nobt-io/frontend
