import AmountEqualSplitPersonList from "./AmountEqualSplitPersonList/AmountEqualSplitPersonList";
import AmountUnequalSplitPersonList from "./AmountUnequalSplitPersonList/AmountUnequalSplitPersonList";
import AmountPercentageSplitPersonList from "./AmountPercentageSplitPersonList/AmountPercentageSplitPersonList";

exports.AmountEqualSplitPersonList = AmountEqualSplitPersonList;
exports.AmountUnequalSplitPersonList = AmountUnequalSplitPersonList;
exports.AmountPercentageSplitPersonList = AmountPercentageSplitPersonList;
