#!/usr/bin/env bash

curl https://sentry.io/api/0/organizations/nobtio/releases/ \
  -X POST \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
  -d '
    {
      "version": "test",
      "refs": [
        {
          "repository": "nobt-io/frontend",
          "commit": "test"
        }
      ],
      "projects": [
        "frontend"
      ]
    }
  '

for f in dist/*.{js,css,map}
do
  FILE_NAME=$(basename $f)

  curl https://sentry.io/api/0/projects/nobtio/frontend/releases/${TRAVIS_COMMIT}/files/ \
    -X POST \
    -H "Authorization: Bearer ${SENTRY_AUTH_TOKEN}" \
    -F file=@"${f}" \
    -F name="~/${FILE_NAME}"
done
