name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source-code
        uses: actions/checkout@v1

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.15

      - uses: actions/cache@v1
        name: Cache node_modules
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-

      - uses: actions/cache@v1
        name: Cache cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn run prettier

      - name: Run linter
        run: yarn run lint

      - name: Run tests
        run: yarn run test

      - name: Build bundle
        run: yarn run build

      - name: Run UI tests
        run: cypress/run.sh

      - name: Upload snapshot archive
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: snapshots
          path: ./cypress/integration/__image_snapshots__

      - name: Upload video recordings
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: video-recordings
          path: ./cypress/videos

      - name: Upload generated bundle
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source-code
        uses: actions/checkout@v1

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10.15

      - uses: actions/cache@v1
        name: Cache node_modules
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-

      - uses: actions/cache@v1
        name: Cache cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cypress-

      - name: Install dependencies
        run: yarn

      - name: Download bundle
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Notify sentry about new release
        run: .sentry/new-release.sh
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist

      - name: Notify sentry about new deployment
        run: .sentry/new-deployment.sh
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    needs: build
    if: github.ref == 'refs/heads/master'
